services:
  - type: web
    name: deep-research-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FIRECRAWL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false